spring:
  profiles:
    active: prd
busi:
  ops: ABCD
  pwd: '{cipher}c92b52bdbfe07003d13c0e0132c7240f22885b4dbc6ee3c59ac432d125018f23'
---
spring:
  profiles: dev
  application:
    name: client-dev
server:
  port: 8080
myconfigtest: 
  config-client-dev8080
democonfigclient:
  message: hello spring dev
---
spring:
  profiles: prd
  application:
    name: client-prd
server:
  port: 8082
myconfigtest: 
  config-client-prd8081
democonfigclient:
  message: hello spring prd
