spring:
  profiles:
    active: prd
---
spring:
  profiles: dev
  application:
    name: client-dev
server:
  port: 8080
---
spring:
  profiles: prd
  application:
    name: client-prd
server:
  port: 8081
