spring:
  profiles:
    active: prd
busi:
  ops: Y
  pwd: '{cipher}09725e1a76c0ee22fa1a28f0f03ce7a9c0e52d80a045de320b77e07df8e2ba53'
---
spring:
  profiles: dev
  application:
    name: client-dev
server:
  port: 8080
myconfigtest: 
  config-client-dev8080
democonfigclient:
  message: hello spring dev
---
spring:
  profiles: prd
  application:
    name: client-prd
server:
  port: 8082
myconfigtest: 
  config-client-prd8081
democonfigclient:
  message: hello spring prd
