spring:
  profiles:
    active: prd
busi:
  ops: Y
  pwd: '{cipher}6b2f3ed63286859dac9ae71ea69d973828a1575ab0316287ede5386bfcdfd7b6'
---
spring:
  profiles: dev
  application:
    name: client-dev
server:
  port: 8080
myconfigtest: 
  config-client-dev8080
democonfigclient:
  message: hello spring dev
---
spring:
  profiles: prd
  application:
    name: client-prd
server:
  port: 8082
myconfigtest: 
  config-client-prd8081
democonfigclient:
  message: hello spring prd
