spring:
  profiles:
    active: prd
busi:
  ops: Y
  pwd: '${cipher}1d94c7de8c6b3eba27a08bece0ef62a14affc65f5b222c9b16588d4dff0f2274'
---
spring:
  profiles: dev
  application:
    name: client-dev
server:
  port: 8080
myconfigtest: 
  config-client-dev8080
democonfigclient:
  message: hello spring dev
---
spring:
  profiles: prd
  application:
    name: client-prd
server:
  port: 8082
myconfigtest: 
  config-client-prd8081
democonfigclient:
  message: hello spring prd
